### ISSUE TITLE
Cannot find module './sql-database'

### ISSUE THREAD

**Issue by bartekn** [stellar/stellar-payments#28]
`new PaymentsClient` fails with:
```
Error: Cannot find module './sql-database'
      at Function.Module._resolveFilename (module.js:338:15)
      at Function.Module._load (module.js:280:25)
      at Module.require (module.js:364:17)
      at require (module.js:380:17)
      at Object.<anonymous> (/Users/bartek/stellar-api/node_modules/stellar-payments/lib/client.js:5:13)
```
Affected versions: 0.4.1

**Comment by bartekn** [comment]
Fixed in 0.4.2.
